# Generated by Django 3.0.5 on 2020-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='avatar',
            field=models.FileField(default='/media/avatars/default.svg', upload_to='media/avatars/'),
        ),
    ]
