# Generated by Django 3.0.5 on 2020-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200502_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
