# Generated by Django 3.0.5 on 2020-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_name',
            new_name='prev_image',
        ),
        migrations.AddField(
            model_name='articledetail',
            name='image',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
